# Generated by Django 4.0 on 2024-05-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importfiles', '0004_initialuploadedfile_validation_passed_filemetadata'),
        ('projects', '0002_alter_projectteamrole_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.TextField()),
                ('analysis_name', models.CharField(max_length=200)),
                ('sampled_units_count', models.IntegerField()),
                ('sample_name', models.TextField()),
                ('files', models.ManyToManyField(to='importfiles.InitialUploadedFile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spm', models.FloatField()),
                ('random_seed', models.IntegerField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
            ],
        ),
    ]
