# Generated by Django 4.0 on 2024-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisparameters',
            name='generate_random_seed',
            field=models.BooleanField(default=True),
        ),
    ]
