# Generated by Django 4.0 on 2024-04-15 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musauth', '0001_initial'),
        ('projects', '0002_projectteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='id',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='incharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_incharge', to='musauth.mususer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectteam',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_manager', to='musauth.mususer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectteam',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_partner', to='musauth.mususer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectteam',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectteam',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
