# Generated by Django 4.0 on 2024-05-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musauth', '0001_initial'),
        ('importfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialuploadedfile',
            name='by_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='musauth.mususer'),
            preserve_default=False,
        ),
    ]
