# Generated by Django 4.0 on 2024-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importfiles', '0002_initialuploadedfile_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialuploadedfile',
            name='txt_column_delimiter',
            field=models.CharField(default='', max_length=5),
        ),
    ]
