# Generated by Django 4.0 on 2024-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importfiles', '0004_initialuploadedfile_validation_passed_filemetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialuploadedfile',
            name='date_processed',
        ),
        migrations.AddField(
            model_name='initialuploadedfile',
            name='decimal_separator',
            field=models.CharField(default='.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialuploadedfile',
            name='thousand_separator',
            field=models.CharField(default=',', max_length=10),
            preserve_default=False,
        ),
    ]
