# Generated by Django 4.0 on 2024-05-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importfiles', '0006_alter_initialuploadedfile_decimal_separator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='importfiles.initialuploadedfile'),
        ),
    ]
