# Generated by Django 4.0 on 2024-05-20 21:27

from django.db import migrations, models
import importfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('importfiles', '0007_remove_filemetadata_id_alter_filemetadata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialuploadedfile',
            name='initial_file',
            field=models.FileField(upload_to=importfiles.models.project_files_folder),
        ),
    ]
